version: 0.2
phases:
  preBuild:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - ./**/*
  discard-paths: no
  baseDirectory: built
cache:
  paths:
    - ./node_modules    
