version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - ./**/*
  discard-paths: no
  base-directory: built
cache:
  paths:
    - ./node_modules    
