version: 0.2

phases:
  install:
    commands:
      - npm install --global gulp-cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm install
      - gulp build
artifacts:
  files:
    - **/*
  discard-paths: no
  base-directory: built