version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  name: BuildOutput
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'built'
cache:
  paths:
    - ./node_modules
